name: unit_7_alanan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.4.0
  http: ^0.13.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
